### ISSUE TITLE
Better syntax highlighting of decompiled code

### ISSUE THREAD

**Issue by PeterMatula** [avast/retdec-r2plugin#3]
The original plugin implementation uses some JavaScript library to syntax highlight the C code. It is not very nice - it often does not highlight some types (e.g. `uint64_t`) and so on.

Study how [r2ghidra](https://github.com/radareorg/r2ghidra-dec) does it and use the same solution if possible. 

If necessary, use tokens provided by [RetDec's JSON C output](https://github.com/avast/retdec/wiki/Decompiler-outputs).

**Comment by xkubov** [comment]
Implemented in #6
