### ISSUE TITLE
Use RetDec's JSON output for ASM <-> C mapping

### ISSUE THREAD

**Issue by PeterMatula** [avast/retdec-r2plugin#4]
The new [RetDec JSON C output](https://github.com/avast/retdec/wiki/Decompiler-outputs) contains info on token assembly addresses.

Use this info for ASM <-> C code association.

Study how [r2ghidra](https://github.com/radareorg/r2ghidra-dec) does it and use the same solution if possible.

**Comment by PeterMatula** [comment]
Study the r2 feature called _panel mode_. It looked very cool when pancake showed it in r2con 2019. r2ghidra probably uses it. If id does not, r2dec should.

**Comment by xkubov** [comment]
This was implemented in #6
