### ISSUE TITLE
Register this plugin in r2's package managment

### ISSUE THREAD

**Issue by PeterMatula** [avast/retdec-r2plugin#5]
The plugin should be easily installable using [r2pm](https://github.com/radare/radare2-pm).

Think up a good name for the plugin. `r2retdec` is already taken, so it would be ideal if we can come up with a better name. If we cannot, we may ask if we can take over it. If we cannot, we must make our own name.

**Comment by xkubov** [comment]
Opened PR: https://github.com/radareorg/radare2-pm/pull/97
